/** Meanings of the radicals used in the bundled dataset (shown as memory hooks). */
export const RADICAL_MEANINGS: Record<string, string> = {
  亻: 'person',
  人: 'person',
  讠: 'speech / words',
  冂: 'down box / borders',
  又: 'right hand / again',
  氵: 'water',
  水: 'water',
  高: 'tall',
  米: 'rice',
  艹: 'grass / plants',
  口: 'mouth',
  飞: 'to fly',
  凵: 'open box',
  火: 'fire',
  方: 'square / direction',
  '⻊': 'foot',
  一: 'one',
  十: 'ten',
  几: 'small table',
  日: 'sun / day',
  王: 'king / jade',
  月: 'moon / flesh',
  子: 'child',
  女: 'woman',
};
