import type { HskLevel } from '../types';

// ---------- Grammar content ----------

export interface GrammarExample {
  hanzi: string;
  /** Marked pinyin (tone marks), word-segmented. */
  pinyin: string;
  english: string;
  note?: string;
}

interface ExerciseBase {
  /** Stable id, generated by the loader as `${pointId}-${index}`. */
  id: string;
  /** Instruction shown above the exercise. */
  prompt: string;
  /** Shown after answering (right or wrong). */
  explanation: string;
}

/** Fill the blank (`___`) in a Chinese sentence with one of the options. */
export interface ChoiceExercise extends ExerciseBase {
  type: 'choice';
  sentence: string;
  /** Translation of the full sentence (optional hint). */
  english?: string;
  options: string[];
  /** Index into `options`. */
  answer: number;
}

/** Pick the correct Chinese (hanzi or pinyin) rendering of an English sentence. */
export interface TranslateExercise extends ExerciseBase {
  type: 'translate';
  english: string;
  optionScript: 'hanzi' | 'pinyin';
  options: string[];
  answer: number;
}

/** Spot the sentence that is wrong (or right — the prompt says which). */
export interface ErrorExercise extends ExerciseBase {
  type: 'error';
  options: string[];
  answer: number;
}

/** Arrange the tokens into a sentence. `tokens` is the canonical correct order. */
export interface OrderExercise extends ExerciseBase {
  type: 'order';
  tokens: string[];
  /** Other accepted orders (same multiset of tokens). */
  alternatives?: string[][];
  english: string;
  pinyin?: string;
}

export type OptionExercise = ChoiceExercise | TranslateExercise | ErrorExercise;
export type GrammarExercise = OptionExercise | OrderExercise;
export type ExerciseType = GrammarExercise['type'];

export interface GrammarPoint {
  id: string;
  hskLevel: HskLevel;
  title: string;
  /** Short Chinese label, e.g. "是". */
  titleHanzi?: string;
  /** Structure formula, tokens separated by " + "; alternatives separated by "  ·  ". */
  pattern: string;
  /** One-line summary for list cards. */
  summary: string;
  /** Paragraphs; `**bold**` is supported. */
  explanation: string[];
  /** Common mistakes / notes. */
  mistakes: string[];
  examples: GrammarExample[];
  exercises: GrammarExercise[];
}

// ---------- Learning paths ----------

export interface VocabStep {
  id: string;
  type: 'vocab';
  title: string;
  wordIds: string[];
}

export interface GrammarStep {
  id: string;
  type: 'grammar';
  grammarId: string;
}

export type PathStep = VocabStep | GrammarStep;

export interface PathUnit {
  id: string;
  title: string;
  goal: string;
  steps: PathStep[];
}

export type PathIcon = 'sprout' | 'plane' | 'bridge' | 'music' | 'mountain' | 'crown';

export interface LearningPath {
  id: string;
  title: string;
  description: string;
  icon: PathIcon;
  units: PathUnit[];
}
